# Generated by Django 4.1.2 on 2024-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_has_sizes"),
        ("profiles", "0002_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ManyToManyField(
                related_name="product_wishlist", to="products.product"
            ),
        ),
    ]
